// <auto-generated />
using System;
using GuangYuan.GY001.TemplateDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuangYuan.GY001.TemplateDb.Migrations
{
    [DbContext(typeof(GY001TemplateContext))]
    [Migration("20210527063955_21052701")]
    partial class _21052701
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuangYuan.GY001.TemplateDb.BlueprintTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChildrenTemplateIdString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GId")
                        .HasColumnType("int");

                    b.Property<string>("PropertiesString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnName("备注")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("蓝图");
                });

            modelBuilder.Entity("GuangYuan.GY001.TemplateDb.BpFormulaTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlueprintTemplateId")
                        .HasColumnName("蓝图Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChildrenTemplateIdString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsContinue")
                        .HasColumnName("命中并继续")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNumber")
                        .HasColumnName("序号")
                        .HasColumnType("int");

                    b.Property<string>("Prob")
                        .HasColumnName("命中概率")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertiesString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnName("备注")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintTemplateId");

                    b.ToTable("公式");
                });

            modelBuilder.Entity("GuangYuan.GY001.TemplateDb.BpItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlueprintTemplateId")
                        .HasColumnName("公式Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChildrenTemplateIdString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conditional")
                        .HasColumnName("条件属性")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountLowerBound")
                        .HasColumnName("增量下限")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountProb")
                        .HasColumnName("增量概率")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountUpperBound")
                        .HasColumnName("增量上限")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCountRound")
                        .HasColumnName("增量取整")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnName("新建物品否")
                        .HasColumnType("bit");

                    b.Property<string>("PropertiesChanges")
                        .HasColumnName("属性更改")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertiesString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnName("备注")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariableDeclaration")
                        .HasColumnName("变量声明")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintTemplateId");

                    b.ToTable("物料");
                });

            modelBuilder.Entity("GuangYuan.GY001.TemplateDb.GameItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChildrenTemplateIdString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GId")
                        .HasColumnType("int");

                    b.Property<string>("GenusIdString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertiesString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnName("备注")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates");
                });

            modelBuilder.Entity("GuangYuan.GY001.TemplateDb.BpFormulaTemplate", b =>
                {
                    b.HasOne("GuangYuan.GY001.TemplateDb.BlueprintTemplate", "BlueprintTemplate")
                        .WithMany("FormulaTemplates")
                        .HasForeignKey("BlueprintTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuangYuan.GY001.TemplateDb.BpItemTemplate", b =>
                {
                    b.HasOne("GuangYuan.GY001.TemplateDb.BpFormulaTemplate", "FormulaTemplate")
                        .WithMany("BptfItemTemplates")
                        .HasForeignKey("BlueprintTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
